######################################################################
# Automatically generated by qmake (2.01a) Fri May 22 22:09:29 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

# Input
HEADERS += render_area.h stomp_viewer.h
SOURCES += main.cc render_area.cc stomp_viewer.cc
RESOURCES += stomp_viewer.qrc
LIBS += -lm -lstomp
